Migrate /notify to /volunteer/admin/notify
emfcamp/Website pull request #1013
Opened 2022-02-24 19:46 UTC by idnorton

Move and update notify to new location prior to improving notify.

Ref #869

2022-02-25 00:01 UTC, marksteward requested changes
I think this one should be something like `volunteer_notify`. The name is used as a prefix for handlers, so referencing the `notify_email` handler in other parts of the app would then be something like `url_for("volunteer_notify.notify_email")`.

2022-02-25 20:29 UTC, idnorton commented
> I think this one should be something like `volunteer_notify`. The name is used as a prefix for handlers, so referencing the `notify_email` handler in other parts of the app would then be something like `url_for("volunteer_notify.notify_email")`.

@marksteward are you saying that it shouldn't be located at the path it is or something else?

2022-02-25 20:47 UTC, idnorton commented
Based on the conversation we had on Thu Nov 04 2021 I think the intention is to remove the email sending aspects of this and use the shared libraries that the admin UI uses rather than having duplicate mechanisms, that can then take care of queueing and handing sending the messages as it does for the major admin notifications.

I'd like to restrict this change to a simple move and follow next steps with updating what;s there to better fit our needs rather than trying to do all of it in a single PR.

Much more a fan of lots of small PRs than a small number of huge PRs.

2022-02-27 12:50 UTC, marksteward approved these changes

2022-02-27 12:50 UTC, merged