Attendee content
emfcamp/Website pull request #1123
Opened 2022-05-08 22:00 UTC by jellybob

Provide an interface for attendees to add their own content to the schedule.

Venues can be associated with a village (only village members can add content to it), can be flagged as being for scheduled content only (only content from the CFP can go there), or neither (anyone can add content there, for places like the bar).

Content added via this path immediately jumps to a finalised state, and is flagged as being user scheduled. Still to do is making slotmachine respect that and not attempt to reschedule it or put it somewhere else.

2022-05-08 22:06 UTC, Jonty commented
We're only putting CFP-content in the villages at certain times and the rest of the time the village can do whatever they like. Does this currently work in that situation?

2022-05-08 22:10 UTC, jellybob commented
I've not tried it yet, but this should allow slotmachine to schedule CFP content at any times the village isn't already running something in their workshop. There's no validation to prevent a village member scheduling content in a workshop at the time as CFP content right now though.

2022-05-09 00:01 UTC, Jonty commented
I think it's ok for villages to do that as they might be running more than one thing at once, but we definitely need to warn them when this happens. And maybe us.

2022-05-10 22:49 UTC, marksteward requested changes

2022-05-10 22:49 UTC, marksteward commented on migrations/versions/7c8d52a17f8f_add_village_venues.py
> +down_revision = '1012d60b8c68'
As I've just merged #1128 you'll need to change this to `822ce04a81a2`. Probably easiest to do `./flask db downgrade` twice, then rebase/merge, make the change and upgrade 3 times.

2022-05-13 22:36 UTC, marksteward approved these changes

2022-05-13 22:45 UTC, marksteward approved these changes

2022-05-17 19:03 UTC, merged