Encourage villages to make wiki pages
emfcamp/Website pull request #1388
Opened 2024-03-09 11:22 UTC by mscroggs

Resolves #1370

2024-03-10 20:44 UTC, russss requested changes

2024-03-10 20:44 UTC, russss commented on templates/_footer.html
> +w<footer role="contentinfo">
Looks like a "w" has crept in here

2024-03-11 07:21 UTC, mscroggs commented on templates/_footer.html
> +w<footer role="contentinfo">
```suggestion
<footer role="contentinfo">
```

2024-03-11 08:17 UTC, russss approved these changes

2024-03-11 08:17 UTC, merged