Add content note and video privacy information to feeds
emfcamp/Website pull request #1719
Opened 2024-06-01 15:17 UTC by edk0

It's been annoying me that these aren't there

2024-06-01 17:21 UTC, lukegb commented on apps/schedule/feeds.py
> +    if event["type"] in ("talk", "lightning talk", "performance") and event["video_privacy"] != "public":
Is the type actually `lightning talk` at this point, or is it `lightningtalk`.

2024-06-01 18:22 UTC, marksteward requested changes

2024-06-01 18:22 UTC, marksteward commented on apps/schedule/feeds.py
> +    if event["type"] in ("talk", "lightning talk", "performance") and event["video_privacy"] != "public":
Should be `lightningtalk`, yep

2024-06-02 11:20 UTC, edk0 commented
Lightning talks are untestable here and I only really added them because they made conceptual sense; they don't appear in the schedule afaik. Also I can't test performances because I can't make them recordable locally, did we do that via the db?

Anyway I fixed the type thing in theory, and it still looks ok for talks.

2025-08-12 20:12 UTC, SamLR commented
Can we hold off on this as the content/cfp system is going to be re-written

2025-08-20 08:21 UTC, closed without merging