953 Volunteer admin UI menus
emfcamp/Website pull request #955
Opened 2021-09-28 18:09 UTC by idnorton

* Remove settings menu and move items to menu bar
* Reorder loading of modules to make menu items alphabetical

2021-09-28 19:44 UTC, ormiret requested changes

2021-09-28 19:44 UTC, ormiret commented on apps/volunteer/admin/venue.py
> ++volunteer_admin.add_view(VolunteerModelView(VolunteerVenue, db.session, name="Venues"))
spare + there

2021-09-28 19:57 UTC, idnorton commented on apps/volunteer/admin/venue.py
> ++volunteer_admin.add_view(VolunteerModelView(VolunteerVenue, db.session, name="Venues"))
Dammit, fixed

2021-10-04 17:13 UTC, ormiret approved these changes

2021-10-04 18:12 UTC, merged